### ISSUE TITLE
Only build PRs once

### ISSUE THREAD

**Issue by awikkerink** [BrightspaceUI/icons#115]
Both push/pr builds are being run for PR commits. This can make the tests run longer, since SauceLabs only allows 6 concurrent sessions, so one build is blocked when the other runs.

Solution: Either turn off PR builds, or push builds.
https://travis-ci.org/BrightspaceUI/icons/settings

Alternatively, only open PRs from forks. (Currently, forked PR builds won't work because the SAUCE_USERNAME is encrypted)

**Comment by dlockhart** [comment]
Closing, as the settings in Travis have been updated.
