### ISSUE TITLE
Add offscreen-description?

### ISSUE THREAD

**Issue by capajon** [BrightspaceUI/icons#151]
Often we'll want a screen-reader friendly description to go along with an icon.

For example recently I was using the dot icon in the recent grades widget to indicate if a grade item is new or not.  I created a sibling d2l-offscreen element to d2l-icon with shows/hide logic that matches the d2l-icon.  It is fine, but it would have been nicer to do something like <d2l-icon offscreen-text="New item" ... ></d2l-icon>.  Beyond being simpler as a consumer, in this case I actually also want the off screen text and icon to be tightly coupled.

I'm happy to add this and will do so, but I wanted to confirm if this is a good thing to add or not before doing the work (which is not a lot of course).

**Comment by dbatiste** [comment]
I think the attribute could just be called `title`.  The fact that it's offscreen is sort of an internal implementation detail.  If all browsers properly supported, it would actually be possible to apply a `<title>` element as first child of an `svg`, which although also an internal detail, would not be offscreen at all.  In addition, it would display a tooltip, which can be helpful for sighted users.

**Comment by dlockhart** [comment]
+1 to solving this for sighted users as well -- I'm guessing they also have a hard time knowing what an orange dot means.

I think design has some larger ideas around tooltips beyond just the `title` attribute. Specifically it'd be great to show the tooltip on-focus (for focusable things) to help out keyboard-only users. Also, the implementation of tooltips will likely fall outside of `<d2l-icon>`, especially if we want to use tooltips from other components like buttons and menus.

**Comment by dbatiste** [comment]
I think Nick D. has done some design for the tooltips.  We might be able to make some headway on that.  :)

**Comment by capajon** [comment]
Sure I'll close this in favor of the tool tip work that will be superior to any offscreen solution.  I just tested using title right now and it worked well enough for me (in NVDA at least) so I prefer the simpler solution (that might also help some sighted users).  Thanks!

**Comment by dlockhart** [comment]
Cool. `aria-label="whatever you want"` may work well too, although no tooltip.
