### ISSUE TITLE
Question: Should d2l-icon-button support aria-label attribute on the nested button?

### ISSUE THREAD

**Issue by mdgbayly** [BrightspaceUI/icons#167]
Looking to upgrade some of our components to v4 of d2l-icons, specifically for d2l-icon-button.

We currently set an aria-label on our v3 d2l-icon-buttons. When I upgrade to v4 we no longer get a announcements in NVDA for these labels.  

It looks like d2l-icon-button sets a title attribute on the nested button but this is not exposed as a property and I don't think it is used by screen readers anyway.

Let me know if we should allow and aria-label attribute to be passed through to the nested button and if so I'll create a PR.

**Comment by dbatiste** [comment]
That's interesting.  The text inside the inner button should get announced, same as a native button.

On a related note, calling native `focus` on `d2l-icon-button` should delegate focus to the inner button.  There's a couple ways to go about that - one such way is to use our [d2l-focusable behavior](https://github.com/Brightspace/d2l-polymer-behaviors-ui/blob/master/d2l-focusable-behavior.html), as we do with `d2l-button` [here](https://github.com/BrightspaceUI/button/blob/master/d2l-button.html#L106) and decorate the focusable element with the `.d2l-focusable` class.

**Comment by mdgbayly** [comment]
Ah - i think that probably explains it - we've not been using it as it was designed to be used. Our team had been adding aria-labels to the v3 d2l-icon-button and leaving the element content empty, when they should actually have been setting the element content to the text and not bothering with an aria-label.
Will update our usages. Thanks!

**Comment by jwong-d2l** [comment]
@mdgbayly @dbatiste This is something our team found:

> Something weird I found: Chrome needs the aria-label for d2l-icon-button to be read out correctly, and Firefox needs the text within the tags. So I added both to make them both function.
(By "read out correctly", I meant that when the button gets focus, NVDA should read out the associated text exactly once, along with "clickable" and "button")

Is that normal? Are we supposed to pass the text in the label and the tag?

**Comment by dbatiste** [comment]
Note: `d2l-icon-button` no longer exists.  It's replacement is in the button repo, [d2l-button-icon](https://github.com/BrightspaceUI/button/blob/master/d2l-button-icon.html#L105).  The icons repo just has icons.  

Anyway, it appears to accept `text` and `aria-label` attributes, and it does not render slotted content so that may make this moot.  Nevertheless, I would still expect slotted text of a button element to be announced, regardless of browser and screen reader.  Have you done any testing with `d2l-button-icon`?

**Comment by jwong-d2l** [comment]
We can't use d2l-button-icon because they're too small.  Take a look at https://github.com/BrightspaceUI/button/issues/130.

**Comment by dlockhart** [comment]
A solution to this has been discussed at the design level -- I'll follow up with you offline. Well... online, but not in here. :)
